
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('events').del()
    .then(function () {
      // Inserts seed entries
      return knex("events").insert([
        {
          thumbnail: "",
          name: "Ride-In Movies in the Park",
          location: "Rancho Del Mar Park",
          address: "748 W Guadalupe Rd",
          city: "Mesa",
          state: "AZ",
          zipcode: "85210",
          state_date: "07-07-2019",
          end_date: "07-07-2019",
          start_time: "7:45 PM",
          end_time: "9:45 PM",
          recurring: false,
          frequency: "",
          cost: "$0.00",
          ages: "All ages; family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Kids Swim Free",
          location: "Kiwanis Recreation Center",
          address: "6111 S All American Way",
          city: "Tempe",
          state: "AZ",
          zipcode: "85823",
          state_date: "07-17-2019",
          end_date: "07-23-2019",
          start_time: "11:30 AM",
          end_time: "3:30 PM",
          recurring: true,
          frequency: "Weekly",
          cost: "$0.00",
          ages: "5 and under;6 to 10;adults;seniors;family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Fall into Fitness",
          location: "",
          address: "67 W Culver St",
          city: "Phoenix",
          state: "AZ",
          zipcode: "85003",
          state_date: "07-23-2019",
          end_date: "07-23-2019",
          start_time: "5:45 PM",
          end_time: "7:00 PM",
          recurring: false,
          frequency: "",
          cost: "$5.00",
          ages: "6 to 10;11-18;adults;seniors;family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Discount Tire Free Family Sunday",
          location: "Phoenix Art Museum",
          address: "1625 N Central Ave",
          city: "Phoenix",
          state: "AZ",
          zipcode: "85004",
          state_date: "07-26-2019",
          end_date: "07-26-2019",
          start_time: "12:00 PM",
          end_time: "5:00 PM",
          recurring: false,
          frequency: "",
          cost: "$0.00",
          ages: "All ages; family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Chronic Disease Self Management Class",
          location: "Andara Senior Living",
          address: "11415 N 114th St",
          city: "Scottsdale",
          state: "AZ",
          zipcode: "85259",
          state_date: "07-30-2019",
          end_date: "08-27-2019",
          start_time: "1:30 PM",
          end_time: "3:30 PM",
          recurring: true,
          frequency: "Weekly",
          cost: "$10.00",
          ages: "Seniors",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Sunrise Hike",
          location: "White Tank Mountain Regional Park",
          address: "20304 W White Tank Mountain Rd",
          city: "Waddell",
          state: "AZ",
          zipcode: "85355",
          state_date: "08-03-2019",
          end_date: "08-03-2019",
          start_time: "5:30 AM",
          end_time: "7:00 AM",
          recurring: false,
          frequency: "",
          cost: "$2.00",
          ages: "All ages; family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Field Observations: Sunrise",
          location: "Cave Creek Regional Park",
          address: "37900 E Cave Creek Pkwy",
          city: "Cave Creek",
          state: "AZ",
          zipcode: "85331",
          state_date: "08-12-2019",
          end_date: "08-12-2019",
          start_time: "6:00 AM",
          end_time: "8:00 AM",
          recurring: false,
          frequency: "",
          cost: "$0.00",
          ages: "6 to10;11-18;adults;seniors",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Hiking with Friends of Estrella",
          location: "Estrella Mountain Regional Park",
          address: "14805 W Vineyard Ave",
          city: "Goodyear",
          state: "AZ",
          zipcode: "85338",
          state_date: "08-20-2019",
          end_date: "08-20-2019",
          start_time: "9:30 AM",
          end_time: "10:30 AM",
          recurring: false,
          frequency: "",
          cost: "$0.00",
          ages: "All ages; family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Bike to Work Day Tempe",
          location: "",
          address: "5120 S Rural Rd",
          city: "Tempe",
          state: "AZ",
          zipcode: "85282",
          state_date: "09-07-2019",
          end_date: "09-07-2019",
          start_time: "7:00 AM",
          end_time: "9:00 AM",
          recurring: false,
          frequency: "",
          cost: "$0.00",
          ages: "All ages; family friendly",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        },
        {
          thumbnail: "",
          name: "Archery 101",
          location: "Estrella Mountain Regional Park",
          address: "14805 W Vineyard Ave",
          city: "Goodyear",
          state: "AZ",
          zipcode: "85338",
          state_date: "09-13-2019",
          end_date: "09-13-2019",
          start_time: "9:00 AM",
          end_time: "12:30 PM",
          recurring: false,
          frequency: "",
          cost: "$5.00",
          ages: "6 to 10;11-18;adults;seniors",
          description:
            "A brief description of the event goes here...learn about the plants in our area, how different parts were used as sustenance and cautions that need to be taken when preparing them. Participants receive take-home information that includes how to grow edibles in your back yard.",
          phone: "602-555-1212",
          website: ""
        }
      ]);
    });
};
